import Head from "next/head";
import HomepageImage1 from "../Images/Homepage/homepage.svg";
import Image from "next/image";
import Zoom from 'react-reveal/Zoom';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Booz Link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Homepage content  */}
      <div className="w-full h-full">
        <div className="grid grid-cols-1 md:grid-cols-2">
          <div className="flex justify-center items-center">
            <Zoom>
            <div className="p-4 md:p-20 space-y-4 items-center">
              <h2 className=" text-6xl font-semibold">
                <spam className=" text-blue-600">Simple-ize</spam> your advanced
                link.
              </h2>
              <p className="text-sm text-gray-600">
                Share your content to audience and maximize potential
                <br /> of your social bio link in just one click.
              </p>
              <button className="outline-none px-6 py-4 text-white bg-blue-600 rounded-full w-1/2">
                Get started
              </button>
            </div>
            </Zoom>
          </div>
          <div>
            <Zoom>
            <Image src={HomepageImage1} alt="Image 1" />
            </Zoom>
          </div>
        </div>
      </div>
      {/* Homepage content  */}
    </div>
  );
}
