import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Booz Link</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full">
        <div className="grid grid-cols-1 md:grid-cols-2">
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
  );
}
